### ISSUE TITLE
Missing parent specifiers for a:focus

### ISSUE THREAD

**Issue by roman-yagodin** [dnnconsulting/DnnC.Contra#8]
It looks like parent specifiers for the `a:focus` is missing (`dnncontra.css`):

```CSS
.contraC .contentpane a,
.contraC .contentpane a:active,
.contraC .contentpane a:link,
.contraC .contentpane a:visited, a:focus {
   font-weight: 700; }
```

I think it should look like that:

```CSS
.contraC .contentpane a,
.contraC .contentpane a:active,
.contraC .contentpane a:link,
.contraC .contentpane a:visited,
.contraC .contentpane a:focus {
   font-weight: 700; }
```
